#include "global.h"

Motor left1(1,E_MOTOR_GEARSET_06,true,E_MOTOR_ENCODER_COUNTS);
Motor left2(2,E_MOTOR_GEARSET_06,true,E_MOTOR_ENCODER_COUNTS);

Motor right1(9,E_MOTOR_GEARSET_06,false,E_MOTOR_ENCODER_COUNTS);
Motor right2(10,E_MOTOR_GEARSET_06,false,E_MOTOR_ENCODER_COUNTS);

Motor intakeU(5,E_MOTOR_GEARSET_18,false,E_MOTOR_ENCODER_COUNTS);
Motor intakeD(6,E_MOTOR_GEARSET_18,false,E_MOTOR_ENCODER_COUNTS);

Motor rollerR(3,E_MOTOR_GEARSET_18,true,E_MOTOR_ENCODER_COUNTS);
Motor rollerL(11,E_MOTOR_GEARSET_18,false,E_MOTOR_ENCODER_COUNTS);

Imu gyro1(10);
Imu gyro2(12);

Controller master(E_CONTROLLER_MASTER);
